### ISSUE TITLE
Datasets in benchml arxiv paper is missing

### ISSUE THREAD

**Issue by shuaijiang-ustc** [capoe/benchml#17]
Hi, the benchml work is very interesting! However, the datasets used in the arxiv paper is not avaiable since the link, https://github.com/BingqingCheng/linear-regression-benchmarks, is empty.

**Comment by capoe** [comment]
Thanks for bringing this to my attention. The repo is probably still
private. Let me check.

**Comment by shuaijiang-ustc** [comment]
Many thanks, capoe! 

The dataset is available now. 
Well, after I install benchml through pip install, I am trying to test benchml in command line mode since it is easy to follow. Then I cd into qm7 dir and found meta.json file existing already, which is the bmeta command output file. Then I tried to run 'bml --mode benchmark --meta meta.json --models gylm --benchmark_json models/benchmark_dataset.json', it reports error:  .
...
- Exclude 'gylm/gylm' (requested but not available) 
 - Exclude 'gylm_grid/gylm_grid' (requested but not available) 
 - Exclude 'gylm_match/gylm_smooth_match' (requested but not available) 
...
Then I switch gylm to acsf or soap, similar errors appeared indicating nearly all models are unavailable, which I don't understand.

Is that because I didn't fully install benchml or other issues?

Thanks first.

Shuai

**Comment by capoe** [comment]
That's correct, 'pip install benchml' triggers a minimal installation without plugin libraries. See the instructions in the 'Installation' section for how to install these optional dependencies.

**Comment by capoe** [comment]
Btw - we are currently in the process of bumping the version on pypi. I have noticed that the new version resulted in conflicts among some of the plugin libraries (in particular dscribe and gylm) which I need to sort out. Just a heads-up ...

**Comment by shuaijiang-ustc** [comment]
I see. Still, after complete installation, I tried benchmark command with soap descriptor and it's working, so thanks!
